# File: C:\Users\nickg\Projects\second_chair\pubspec.yaml
name: second_chair
description: A legal case management app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.0.0
  provider: ^6.0.0
  table_calendar: ^3.0.0
  path_provider: ^2.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.0.0
  build_runner: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/states_counties.json
    - packages/drift/wasm/sqlite3.wasm
    - packages/drift/wasm/drift_worker.js