# File: C:\Users\nickg\Projects\second_chair\pubspec.yaml
name: second_chair
description: A legal case management app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.26.0  # Latest stable version as of Oct 2023
  provider: ^6.1.2  # Latest stable version
  table_calendar: ^3.1.2  # Latest stable version
  path_provider: ^2.1.4  # Latest stable version
  path: ^1.9.0  # Latest stable version
  flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0  # Match drift version
  build_runner: ^2.4.12  # Latest stable version

flutter:
  uses-material-design: true
  assets:
    - assets/states_counties.json
    - packages/drift/wasm/sqlite3.wasm
    - packages/drift/wasm/drift_worker.js